<?php

return [
    [
        'slug' => 'taza-azul',
        'nombre' => 'Taza azul',
        'categoria' => 'Tazas',
        'descripcion' => 'Taza de cerámica esmaltada a mano. Es una pieza sencilla para uso diario.',
        'precio' => 12.50,
        'stock' => 8,
        'imagen' => 'img/productos/tazas.jpg',
        'alt' => 'Tazas de cerámica artesanal',
    ],
    [
        'slug' => 'jarron-blanco',
        'nombre' => 'Jarrón blanco',
        'categoria' => 'Jarrones',
        'descripcion' => 'Jarrón decorativo de cerámica. Puede usarse con flores secas o como decoración.',
        'precio' => 24.90,
        'stock' => 5,
        'imagen' => 'img/productos/jarrones.jpg',
        'alt' => 'Jarrones de cerámica artesanal',
    ],
    [
        'slug' => 'figura-cabezones',
        'nombre' => 'Figura decorativa',
        'categoria' => 'Decoración',
        'descripcion' => 'Figura de cerámica pintada. Producto pensado para decorar una habitación o estantería.',
        'precio' => 18.00,
        'stock' => 3,
        'imagen' => 'img/productos/cabezones.png',
        'alt' => 'Figuras decorativas de cerámica',
    ],
    [
        'slug' => 'cabeza-ceramica',
        'nombre' => 'Cabeza de cerámica',
        'categoria' => 'Decoración',
        'descripcion' => 'Pieza decorativa de cerámica con acabado artesanal.',
        'precio' => 21.75,
        'stock' => 1,
        'imagen' => 'img/productos/cabeza.jpg',
        'alt' => 'Cabeza decorativa de cerámica',
    ],
    [
        'slug' => 'piedras-pintadas',
        'nombre' => 'Surtido de piedras',
        'categoria' => 'Decoración',
        'descripcion' => 'Surtido de piedras, elige la que más te guste y adóptala!',
        'precio' => 7.90,
        'stock' => 9,
        'imagen' => 'img/productos/piedras.jpeg',
        'alt' => 'Piedras con caras divertidas',
    ],
     [
        'slug' => 'estrella-guapa',
        'nombre' => 'Estrellita',
        'categoria' => 'Decoración',
        'descripcion' => 'Una estrella que ilumina tu vida!',
        'precio' => 12.99,
        'stock' => 1,
        'imagen' => 'img/productos/estrella.jpeg',
        'alt' => 'Estrella con lindo rostro',
    ],

     [
        'slug' => 'figura-patas',
        'nombre' => 'Hombrecillo con pies grandes',
        'categoria' => 'Decoración',
        'descripcion' => 'Un hombre con una talla de pie...un poco grande',
        'precio' => 15.90,
        'stock' => 2,
        'imagen' => 'img/productos/piezudo.jpeg',
        'alt' => 'Hombre con grandes pies',
    ],
];
